[package]
name = "hakobackend-auth-firebase"
version = "0.1.0"
edition = "2021"

[dependencies]
hakobackend-core = { path = "../hakobackend-core" }
async-trait = { workspace = true }
jsonwebtoken = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
