[package]
name = "hakobackend-server"
version = "0.1.0"
edition = "2021"

[dependencies]
hakobackend-core = { path = "../hakobackend-core" }
hakobackend-db-hako = { path = "../hakobackend-db-hako" }
hakobackend-policy = { path = "../hakobackend-policy" }
hakobackend-auth-core = { path = "../hakobackend-auth-core" }
hakobackend-auth-local = { path = "../hakobackend-auth-local" }
hakobackend-auth-github = { path = "../hakobackend-auth-github" }
hakobackend-db-postgres = { path = "../hakobackend-db-postgres" }
hakobackend-db-sqlite = { path = "../hakobackend-db-sqlite" }
hakobackend-db-mysql = { path = "../hakobackend-db-mysql" }
hakobackend-ratelimit = { path = "../hakobackend-ratelimit" }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tower-http = { workspace = true }
toml = { workspace = true }
clap = { workspace = true }
axum-server = { workspace = true }
rustls = { workspace = true }
tokio-stream = { workspace = true }
