[package]
name = "ub-server"
version = "0.1.0"
edition = "2021"

[dependencies]
ub-core = { path = "../ub-core" }
ub-db-hako = { path = "../ub-db-hako" }
ub-policy = { path = "../ub-policy" }
ub-auth-core = { path = "../ub-auth-core" }
ub-auth-local = { path = "../ub-auth-local" }
ub-auth-github = { path = "../ub-auth-github" }
ub-db-postgres = { path = "../ub-db-postgres" }
ub-db-sqlite = { path = "../ub-db-sqlite" }
ub-db-mysql = { path = "../ub-db-mysql" }
ub-ratelimit = { path = "../ub-ratelimit" }
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tower-http = { workspace = true }
toml = { workspace = true }
clap = { workspace = true }
axum-server = { workspace = true }
rustls = { workspace = true }
tokio-stream = { workspace = true }
